### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by acurrieclark** [tzurbaev/laravel-forge-api#12]
One of the issues which crops up now and again (for me, and for users of other Forge SDKs that I have seen) is the current API rate limit. It is currently set at 30 requests/minute.
Is there any way that automatic (perhaps optional) rate limiting could be worked into this SDK? I realise there are ways it could be done externally, but I wonder if it might be worth looking into. More than happy to contribute as ever if you think it is worthwhile.

**Comment by tzurbaev** [comment]
Actually, there're more questions than answers about rate limiting. How exactly should we handle this?

1. Throw RateLimitExceededException? If yes, then the request somehow should be repeated after we're allowed to make requests to the API. How this should be done? Save failed requests to cache/queue and repeat after 30 seconds? I don't think that caching/queueing mechanism should be added to SDK, so this must be controlled in the target application.

2. Or should we ignore failed requests and require SDK's users to repeat them manually?

3. Or even put the script to `sleep($secondsLeftBeforeNextWindow);` (that's the ugliest solution as for me and probably this won't work at all)?

At this moment, the only way I see is to throw exception on `HTTP 429` responses (actually, Guzzle already throws it but we can rename it to more informational one) and let users handle it in their preferred way. What do you think?

**Comment by acurrieclark** [comment]
I have been thinking about this, and I feel that it might be worth offering an option. For example, setting an optional `useRateLimiting` flag on the `$forge` instance to which a closure is passed. The closure provides the rate limiting code, and could pause as required.
I imagine most users will only need to rate limit across one instance of an application, but this would also allow people to code an implementation which rate limited across multiple instances.
I will try and look at how this can be achieved over the next week or so and offer something up.

**Comment by acurrieclark** [comment]
#14 Attempts to address this issue

**Comment by acurrieclark** [comment]
#14
