### ISSUE TITLE
Let's Encrypt Certificate Path

### ISSUE THREAD

**Issue by krisnicolaou** [tzurbaev/laravel-forge-api#13]
Hey There,

There's an issue with the create Let's Encrypt certificate resource or API path. The documentation says it needs to be:
`/api/v1/servers/{serverId}/sites/{siteId}/certificates/letsencrypt`

Your code generates the following:
`/api/v1/servers/{serverId}/sites/{siteId}/letsencrypt`

Within the following file:
`Laravel\Forge\Certificates\Commands\ObtainLetsEncryptCertificateCommand`

The change It needs to be changed from:
```
public function resourcePath()
{
    return 'letsencrypt';
}
```

to:
```
public function resourcePath()
{
    return 'certificates/letsencrypt';
}
```

(sorry, didn't have time to create a pull request)

Thank you,
Kris

**Comment by tzurbaev** [comment]
Hi, @krisnicolaou! The issue your'e reporting about was fixed in v1.3.0, latest version of package as of 2017-06-06 is 1.3.1.

Please, make sure to upgrade to the latest version of the SDK and feel free to reopen this issue if something is still not working.
