### ISSUE TITLE
ListCertificates is not returning a list

### ISSUE THREAD

**Issue by skibradshaw** [tzurbaev/laravel-forge-api#2]
I have confirmed that I am getting a valid Site from SiteManager Class.   Here is my code:

$certificates = new CertificatesManager();
$certificates->list()->from($site)

And here is the response: 
```
GuzzleHttp\Exception\ClientException with message 'Client error: `GET https://forge.laravel.com/api/v1/servers/100050/certificates` resulted in a `404 Not Found` response:
Resource not found.
```

It appears the API call is not providing the 'sites' portion of the API URI call before the certificates.

From the tests, this appears it should be structured as: 
`https://forge.laravel.com/api/v1/servers/1/sites/1/certificates' ` 

What am I missing here?

**Comment by tzurbaev** [comment]
Hi, @skibradshaw!

Thank you for reporting this issue. Unfortunately I'm unable to reproduce the error you're encountering.

Can you, please, try to execute this code and confirm that you still having this issue?

```php
<?php

use Laravel\Forge\Forge;
use Laravel\Forge\ApiProvider;
use Laravel\Forge\Sites\SitesManager;
use Laravel\Forge\Certificates\CertificatesManager;

$forge = new Forge(new ApiProvider('your-api-token'));
$serverId = 'your-server-id';
$siteId = 'your-site-id';

$server = $forge->get($serverId);

$sites = new SitesManager();
$site = $sites->get($siteId)->from($server);

$manager = new CertificatesManager();
$list = $manager->list()->from($site);

foreach ($list as $certificate) {
    echo $certificate->name();
}
```

As for me, this code work properly and `$certificate->name()` returns correct site domain.

However, if I change `$list = $manager->list()->from($site);` to `$list = $manager->list()->from($server);`, I get the exception you've mentioned.

If you're using this package with [Laravel application](https://github.com/tzurbaev/laravel-forge-api/blob/master/docs/getting-started.md#laravel-integration), you can try to run this command instead: https://gist.github.com/tzurbaev/0482b8ccc4f747e19e77d499067589a0

Create new file named `ListForgeCertificates.php` inside your application's `app/Console/Commands` folder and add this command to `app/Console/Kernel.php`'s `$commands` array.

If you're having troubles with registring command, please, refer to Laravel's documentation on [Registering Commands](https://laravel.com/docs/5.4/artisan#registering-commands). 

When you're done, run `php artisan forge:certificates ServerID SiteID` command in your console.

You can get your server and site IDs by visiting Laravel Forge website. Copy IDs from address bar: https://forge.laravel.com/servers/1111/sites/2222, where `1111` is your Server ID and `2222` is your Site ID.

Also, please make sure that you're using latest version of this package. As of 2017-04-08 actual version is **1.1.1**

If everything is done right, you should be able to list your site's certificates. If provided code works and your code still fails, you can paste your listings here and I'll try to help you to resolve the issue.

Hope this will help.

**Comment by skibradshaw** [comment]
Hi Timur,
This works for me, thank you.  I think my issue was that I was trying to list all certificates on the server rather than a specific SiteID certificates.  I corrected that and it works now.  Really appreciate the help.
Thanks,
Tim
