### ISSUE TITLE
Creating a site on LoadBalancer

### ISSUE THREAD

**Issue by ashitvora-zz** [tzurbaev/laravel-forge-api#21]
I am trying to add a site to LoadBalancer server and not an app server.
How can I add a new site to the server and specify the servers to which it should route the requests (instead of specifying git repo and other stuff)?

Thanks!

**Comment by tzurbaev** [comment]
I'm very sorry for the lack of activity from my side on this. If you still have troubles, please, reopen or create new issue. Also, I would glad to review a PR if you have something to share.
