### ISSUE TITLE
Create server sudo and database passwords

### ISSUE THREAD

**Issue by acurrieclark** [tzurbaev/laravel-forge-api#5]
When creating a new server, the [sudo and database passwords are returned outside](https://forge.laravel.com/api-documentation#create-server) outside of the `server` object. With the current implementation, there is no way of accessing these properties.

**Comment by acurrieclark** [comment]
Had another look through and wrote a rather inelegant solution [#6] which relies on replicating the ApiResource `createFromResponse` function. Functional, but perhaps there is a better way?

**Comment by tzurbaev** [comment]
#6 merged.
